import { RoomType, RoomConfig } from './types';

export const DEFAULT_EXCHANGE_RATE = 2.46;

export const DEFAULT_MAZARAT_PRICE_MAD = 500;
export const DEFAULT_FAQIH_PRICE_MAD = 800;

export const INITIAL_ROOM_CONFIG: RoomConfig[] = [
  { 
    id: '1',
    type: RoomType.DOUBLE, 
    count: 1, 
    paxPerRoom: 2,
    hasMadinah: true,
    madinahHotel: '',
    madinahNights: 3,
    madinahPricePerPersonSAR: 0,
    hasMakkah: true,
    makkahHotel: '',
    makkahNights: 5,
    makkahPricePerPersonSAR: 0
  }
];

export const COMPANY_DETAILS = {
  address: "41 Rue Saad Bnou Abi Wakkas, Casablanca 20250",
  phone: "05224-84849",
  legal: "RC: 12345 | Patente: 67890 | IF: 112233 | ICE: 001122334455"
};

export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    newQuote: "New Quotation",
    settings: "Settings",
    logout: "Logout",
    totalQuotes: "Total Quotes",
    confirmed: "Confirmed",
    currentRate: "Current Rate",
    recentQuotes: "Recent Quotations",
    reference: "Reference",
    client: "Client",
    date: "Date",
    pax: "Pax",
    status: "Status",
    actions: "Actions",
    step1: "Accommodations",
    step2: "Flights & Extras",
    step3: "Confirm",
    clientName: "Client Full Name",
    mobile: "Mobile Number",
    roomConfig: "Room Configuration",
    addRoom: "Add Room",
    madinah: "Madinah",
    makkah: "Makkah",
    hotelName: "Hotel Name",
    nights: "Nights",
    pricePerPax: "SAR / Pax / Night",
    flightDetails: "Flight Details",
    airline: "Airline Name",
    priceMadPax: "MAD / Pax",
    visaFees: "Visa Fees",
    transfers: "Transfers",
    transferDetailsPlaceholder: "Enter transfer service details (vehicle type, pickup, etc)...",
    extraServices: "Extra Services (MAD)",
    mazarat: "Mazarat (Visits)",
    faqih: "Faqih (Scholar)",
    financials: "Financials (Per Person Inputs)",
    extraLabel: "Extra Services (MAD/Pax)",
    commissionLabel: "Agent Commission (MAD/Pax)",
    agencyMargin: "Agency Margin (MAD/Pax)",
    summary: "Summary Breakdown",
    totalGlobal: "Total Global Estimated",
    confirmBtn: "Confirm & Download PDFs",
    nbText: "NB: Please note that no reservation has been made. Rates are subject to change at the time of confirmation.",
    servicesInclus: "SERVICES INCLUDED",
    detailsTarifs: "PRICING DETAILS (PER PERSON)",
    financialDetails: "FINANCIAL DETAILS (AGENCY)",
    room: "Room",
    flight: "Flight",
    comm: "Comm (PP)",
    extrasCol: "Extras (PP)",
    margin: "Margin (PP)",
    final: "Final (PP)",
    sarToMadRate: "SAR -> MAD Rate",
    uploadLogo: "Upload Agency Logo"
  },
  fr: {
    dashboard: "Tableau de Bord",
    newQuote: "Nouveau Devis",
    settings: "Paramètres",
    logout: "Déconnexion",
    totalQuotes: "Total Devis",
    confirmed: "Confirmés",
    currentRate: "Taux Actuel",
    recentQuotes: "Devis Récents",
    reference: "Référence",
    client: "Client",
    date: "Date",
    pax: "Pax",
    status: "Statut",
    actions: "Actions",
    step1: "Hébergement",
    step2: "Vols & Extras",
    step3: "Confirmer",
    clientName: "Nom du Client",
    mobile: "Numéro de Mobile",
    roomConfig: "Configuration des Chambres",
    addRoom: "Ajouter Chambre",
    madinah: "Médine",
    makkah: "Makkah",
    hotelName: "Nom de l'Hôtel",
    nights: "Nuits",
    pricePerPax: "SAR / Pers / Nuit",
    flightDetails: "Détails du Vol",
    airline: "Compagnie Aérienne",
    priceMadPax: "MAD / Pers",
    visaFees: "Frais de Visa",
    transfers: "Transferts",
    transferDetailsPlaceholder: "Veuillez ajouter les détails du service de transfert...",
    extraServices: "Services Extras (MAD)",
    mazarat: "Mazarat (Visites)",
    faqih: "Faqih (Savant)",
    financials: "Finances (Saisie Par Personne)",
    extraLabel: "Services Extras (MAD/Pers)",
    commissionLabel: "Commission Agent (MAD/Pers)",
    agencyMargin: "Marge Agence (MAD/Pers)",
    summary: "Résumé",
    totalGlobal: "Total Global Estimé",
    confirmBtn: "Confirmer & Télécharger PDFs",
    nbText: "NB : Veuillez noter qu'aucune réservation n'a été effectuée. Les tarifs sont sujets à changement au moment de la confirmation.",
    servicesInclus: "SERVICES INCLUS",
    detailsTarifs: "DÉTAILS DES TARIFS (PAR PERSONNE)",
    financialDetails: "DÉTAILS FINANCIERS (AGENCE)",
    room: "Chambre",
    flight: "Vol",
    comm: "Comm (PP)",
    extrasCol: "Extras (PP)",
    margin: "Marge (PP)",
    final: "Final (PP)",
    sarToMadRate: "Taux SAR -> MAD",
    uploadLogo: "Télécharger Logo Agence"
  },
  ar: {
    dashboard: "لوحة القيادة",
    newQuote: "عرض سعر جديد",
    settings: "الإعدادات",
    logout: "تسجيل خروج",
    totalQuotes: "إجمالي العروض",
    confirmed: "مؤكدة",
    currentRate: "سعر الصرف",
    recentQuotes: "العروض الأخيرة",
    reference: "مرجع",
    client: "العميل",
    date: "التاريخ",
    pax: "أشخاص",
    status: "الحالة",
    actions: "إجراءات",
    step1: "الإقامة",
    step2: "الطيران والإضافات",
    step3: "تأكيد",
    clientName: "اسم العميل",
    mobile: "رقم الهاتف",
    roomConfig: "تكوين الغرف",
    addRoom: "إضافة غرفة",
    madinah: "المدينة المنورة",
    makkah: "مكة المكرمة",
    hotelName: "اسم الفندق",
    nights: "ليالي",
    pricePerPax: "ريال / شخص / ليلة",
    flightDetails: "تفاصيل الطيران",
    airline: "شركة الطيران",
    priceMadPax: "درهم / شخص",
    visaFees: "رسوم التأشيرة",
    transfers: "نقل",
    transferDetailsPlaceholder: "الرجاء إضافة تفاصيل خدمة النقل...",
    extraServices: "خدمات إضافية (درهم)",
    mazarat: "مزارات",
    faqih: "فقيه",
    financials: "المالية (إدخال لكل شخص)",
    extraLabel: "خدمات إضافية (درهم/شخص)",
    commissionLabel: "عمولة الوكيل (درهم/شخص)",
    agencyMargin: "هامش الوكالة (درهم/شخص)",
    summary: "ملخص",
    totalGlobal: "الإجمالي التقديري",
    confirmBtn: "تأكيد وتحميل PDF",
    nbText: "ملاحظة: يرجى العلم أنه لم يتم إجراء أي حجز. الأسعار قابلة للتغيير عند التأكيد.",
    servicesInclus: "الخدمات المشمولة",
    detailsTarifs: "تفاصيل الأسعار (لكل شخص)",
    financialDetails: "التفاصيل المالية (وكالة)",
    room: "غرفة",
    flight: "طيران",
    comm: "عمولة",
    extrasCol: "إضافات",
    margin: "هامش",
    final: "نهائي",
    sarToMadRate: "سعر صرف الريال -> درهم",
    uploadLogo: "تحميل شعار الوكالة"
  }
};